apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:NYJfTXc3QkuBx/gMRj4FOTQPBKCUEdxmOIObxA4qqiaInqmq,iv:2Pj3iiPUPWt+2m4E1Ed6sWJVyJtIHKVZWmyinzDTQkY=,tag:/fsJyaeq64r35dzcfUqO3Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:8SguS+lVvavEpFYHHCkSpe9fHTN6Vsnk1cDb6oc3coRvG5066bbZa04VCjQieH+FKrtz+EUAEU4BdE14fBfldBDN2V+osZepkGKGVfLVdeAu76SRWHj7ifOKFITp3NQiPhuNb1UV1DRiAQGsBEcPY3LjChPmh8Mw+Wde2Tc62UAUL0qRZkFOSEh+iViNsfSlmpoaiUGpMyu424+4AYVq8U+c021RSf8JH4inaEPCgQ==,iv:R6vu+b/vskqAfmp8EuUvrbrBNFKO6wPb5GDrZkNW00Q=,tag:AYMFcHvmhbEf2NICw0T2gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1043t30nz2s8uj2m7faq9fce83579y806puqpgw92v4a33zzure4qrmx5kl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR1dZVEZKU0lMeEpzVFFt
            NHN6dDhiN3JuTEVQSFV6VjZFNnFBK2F2cmt3Clo5R3NvUHBuNktQS1IzNGlmWVpz
            aUdVckVid0VhRWNROUtBOUtDcXN2ZG8KLS0tIFdRd05Udnk4eTYzVUVUVmpXWFNE
            UmJYUEJnSWM4dTM5T2FXMEp3UzVRWm8KDvrzfacXda5YEv0wPv/YJ+9diL2uuCUr
            fjN56aHEBnOgdAdyy/C+TLm6yuKyxzJCv4Gh7bDhNnxohadwmh25Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T16:29:39Z"
    mac: ENC[AES256_GCM,data:P1sXuVEbMLoBB0qDkZgnGl+MsJMm81cfBFGbF43IAmZ6BW3+kBV2vN3N1Y2NhXWyMFiUFqd+wv9twtiU6sNShpmD9wsJPQQEAHm+9GY5YcK5+lBNpZFWxjg9wOHyfsFcc6KTOBviJKkffoOpRaobUqpXdWhBkN4lLRv5AbIR+lM=,iv:ydCtzBomMqBwhUcbKRs8c4/FyFnSPLP8N0HE9hm3nkQ=,tag:6eY5QNu5Bje+c0lslFDnJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
